language: python
cache: pip
sudo: false

python:
    - 3,5
    - 3.6

before_install:
    - sudo apt-get -qq update

install:
    - pip install -U pip
    - pip install -U aiohttp, pytest

script:
    - pytest
